In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

import pandas as pd
import pickle

In [2]:
df = pd.read_csv("../../LetsGoToTheMovies/dataset/clean/IMDB-Movie-Data-cleaned.csv")
df.head(5)

,Unnamed: 0,Rank,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,0,1,2014,121,8.1,757074,333.13,76.0
1,1,2,2012,124,7.0,485820,126.46,65.0
2,2,3,2016,117,7.3,157606,138.12,62.0
3,3,4,2016,108,7.2,60545,270.32,59.0
4,4,5,2016,123,6.2,393727,325.02,40.0

In [5]:
clean_df = df.drop(["Unnamed: 0"], axis = 1)
clean_df

,Rank,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,2014,121,8.1,757074,333.13,76.0
1,2,2012,124,7.0,485820,126.46,65.0
2,3,2016,117,7.3,157606,138.12,62.0
3,4,2016,108,7.2,60545,270.32,59.0
4,5,2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...
833,994,2010,97,5.9,140900,60.13,37.0
834,995,2012,88,6.7,164088,54.72,48.0
835,997,2007,94,5.5,73152,17.54,46.0
836,998,2008,98,6.2,70699,58.01,50.0
837,1000,2016,87,5.3,12435,19.64,11.0

In [6]:
X = clean_df.drop('Metascore', axis=1)
y = clean_df["Metascore"]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [8]:
reg = LinearRegression()
reg.fit(X,y)

LinearRegression()

In [9]:
r2 = reg.score(X_train,y_train)
print("R^2:", r2)

y_pred = reg.predict(X_test)

R^2: 0.4518171181428129